---
- hosts: all
  remote_user: root
  tasks:
    - name: Run cadvisor
      shell: docker run --volume=:/rootfs:ro --volume=/var/run:/var/run:ro --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --volume=/dev/disk/:/dev/disk:ro --publish=8080:8080 --detach=true --name=cadvisor google/cadvisor:latest
      args: 
        executable: /bin/bash