---
 
- hosts: all
  remote_user: root
  tasks:
    # This task updates servers that use 'yum' and RPM packages
    # by looking for CentOS or RedHat as a distribution name. This
    # will may also pick up modern OracleLinux but OL has a lot of
    # different strings.
  # Remove partition number 1
  - name: Remove a volume group with name vg.services
    lvg:
      vg: centos
      state: absent
      force: yes