---
 
- hosts: all
  remote_user: root
  tasks:
# Gluster volume configuration.
  - name: Check if Gluster volumes already exist.
    shell: "gluster volume info"
    changed_when: false
    register: gluster_volume_info

  - name: Connect to Gluster peers.
    shell: "gluster peer probe {{ item }}"
    register: gluster_peer_probe
    changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
    failed_when: false
    with_items:
        - gfs01
        - gfs02
        - gfs03
        - gfs04
        - gfs05
        - gfs06
        - gfs07
        - gfs08
        - gfs09
        - gfs10
        - gfs11
        - gfs12
        - client01
    when: "'Volume Name: gluster' not in gluster_volume_info.stdout"