---
- hosts: all
  remote_user: root
  tasks:
  - name: create group
    group:
      name: prometheus
      state: present
  - name: create user
    user:
      name: prometheus
      group: prometheus
      createhome: no
      system: yes
      state: present
  - name: Download prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.3.2/prometheus-2.3.2.linux-amd64.tar.gz
      dest: /root/prometheus-2.3.2.linux-amd64.tar.gz
      mode: 0440    
  - name: create opt directory for prometheus
    file:
      path: /opt/prometheus
      owner: prometheus
      group: prometheus
      state: directory
  - name: Extract Prometheus in opt
    shell: tar -xfv ~/prometheus-2.3.2.linux-amd64.tar.gz /opt/prometheus-2.3.2.linux-amd64
    args:
      executable: /bin/bash
  - name: create symlink to prometheus folder
    file:
      path: /opt/prometheus-2.3.2.linux-amd64
      state: link
      src: /opt/prometheus
  - name: create symlink to prometheus yml
    file:
      path: /opt/prometheus/prometheus.yml
      state: link
      src: /etc/prometheus.yml
  - name: create opt directory for prometheus/data
    file:
      path: /opt/prometheus/data
      owner: prometheus
      group: prometheus
      state: directory
  - name: copying prometheus yml
    copy:
      src: ~/Documentos/personal/ansible-playbooks/files_monit/prometheus.yml
      dest: /etc/prometheus.yml
      owner: root
      group: root
      mode: 0777
  - name: copying systemd service
    copy:
      src: ~/Documentos/personal/ansible-playbooks/files_monit/prometheus.service
      dest: /etc/systemd/system/prometheus.service
      owner: root
      group: root
      mode: 0644
  - name: configure systemd to use service
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: prometheus